### PR TITLE
Adding missing people

### PR DESCRIPTION
**Pull request by castelao**
Following @grantbuster 's suggestion on ordering - As defined by GitHub on contributions.

Please, double check your personal information and approve it as a review. Also, let me know if you would like to change anything.

### CODE REVIEW

**Comment by ppinchuk** [comment]
@castelao Sorry to be nitpicky here, but can we set `given-names: Pavlo` for mine? I typically like to use my full legal name for citations/authorship

**Review by bnb32 — COMMENTED** [review]
This is Andrew's orcid 0000-0002-7268-1883. Too many Ryan Kings to search through.

**Review by malihass — APPROVED** [review]
Thanks for adding this info :-)

**Comment by grantbuster** [comment]
Ryan Kings: 0000-0002-0591-7139

**Review by ppinchuk — APPROVED** [review]
Thanks!!

**Comment by castelao** [comment]
OK, I'm moving this one forward. We can always open another PR to make further changes.

**Pull request merged**
